# Parallel computing with MPI-3 RMA and Julia

<br/>
### JuliaCon 2018
<br/>
[Bart Janssens](https://github.com/barche)

## Bird's eye view

1. Motivation
1. Classic MPI message passing
2. Native Julia parallelism
3. MPI-3 one-sided "Remote Memory Access" (RMA)
4. Applications:
    - MPI Arrays
    - Julia IO on MPI
    - New clustermanager

## Motivation

Julia already has multicore processing support, so why MPI?

* The standard communication library on scientific clusters
* Interfacing with legacy Fortran/C/C++ code
* Optimal MPI implementations exist for specific interconnects (e.g. InfiniBand)
* Thanks to `ccall`, integration is cheap and easy and MPI can be made more friendly to Julia programmers

## The MPI way
* MPI: Message passing interface
* Original: **cooperative** communication

|Rank 0|Rank 1|
|---|---|---|
|Init()|Init()|
|mymessage = "Hi 1!"||
|Send(mymessage,1)|Recv(buffer)|
|Finalize()|Finalize()|



The same program is sent to all ranks:
```julia
using MPI

MPI.Init()

const comm = MPI.COMM_WORLD
const rank = MPI.Comm_rank(comm)
const tag = 0

if rank == 0
  msg = unsafe_wrap(Vector{UInt8},"Hi 1!")
  println("Sending message from rank 0 to rank 1")
  MPI.Send(msg, 1, tag, comm)
elseif rank == 1
  rec_buf = fill(UInt8('_'), 10)
  MPI.Recv!(rec_buf, 0, tag, comm)
  println("Received message $(String(rec_buf)) from rank 0")
end

println("Rank $rank is finalizing.")
MPI.Finalize()
```

Output of `mpirun -np 4 julia --project src/sendrecv.jl`:

```text
Sending message from rank 0 to rank 1
Rank 3 is finalizing.
Rank 2 is finalizing.
Received message Hi 1!_____ from rank 0
Rank 0 is finalizing.
Rank 1 is finalizing.
```

### Collective calls
* Send/Receive works only between two processes
* Collective calls exist, e.g. summing an array:

```julia
using MPI

MPI.Init()

const comm = MPI.COMM_WORLD
const rank = MPI.Comm_rank(comm)
const root = 0

vec = fill(1,10)
s = MPI.Reduce(sum(vec), +, root, comm) # MUST be called on all ranks
println("Sum on rank $rank: $(repr(s))")

MPI.Finalize()

```


Output of `mpirun -np 4 julia --project src/reduce.jl`:

```text
Sum on rank 2: nothing
Sum on rank 3: nothing
Sum on rank 0: 40
Sum on rank 1: nothing
```

Or using `Allreduce`:
```text
Sum on rank 2: 40Sum on rank 3: 40
Sum on rank 1: 40

Sum on rank 0: 40
```

## The Julia way
* One-sided
* Remote references and remote call
* Directed by a "master" process.
* "Workers" do the actual work and can be started and stopped using `addprocs` and `rmprocs`

Starting up:

In [1]:
using Distributed
addprocs(3)

3-element Array{Int64,1}:
 2
 3
 4

Creating some arrays remotely:

In [50]:
remote_arrays = [@spawnat w fill(myid(),10) for w in workers()]

3-element Array{Future,1}:
 Future(2, 1, 102, nothing)
 Future(3, 1, 103, nothing)
 Future(4, 1, 104, nothing)

Fetching the result:

In [51]:
fetch(remote_arrays[1])

10-element Array{Int64,1}:
 2
 2
 2
 2
 2
 2
 2
 2
 2
 2

Compute the sum:

In [52]:
sums = map(remote_arrays) do x
    @spawn begin
        println("Computing sum for $x on process $(myid())")
        return sum(fetch(x))
    end
end;

      From worker 3:	Computing sum for Future(3, 1, 103, nothing) on process 3
      From worker 4:	Computing sum for Future(4, 1, 104, nothing) on process 4
      From worker 2:	Computing sum for Future(2, 1, 102, Some([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])) on process 2


In [53]:
sum(fetch.(sums))

90

In [54]:
sums

3-element Array{Future,1}:
 Future(2, 1, 106, Some(20))
 Future(3, 1, 107, Some(30))
 Future(4, 1, 108, Some(40))

Or using the higher level `@distributed` macro:

In [55]:
@distributed (+) for x=remote_arrays
    println("Computing sum for $x on process $(myid())")
    sum(fetch(x))
end

      From worker 2:	Computing sum for Future(2, 1, 102, Some([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])) on process 2
      From worker 3:	Computing sum for Future(3, 1, 103, Some([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])) on process 3
      From worker 4:	Computing sum for Future(4, 1, 104, Some([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])) on process 4


90

## MPI one-sided communication
* First introduced in MPI-2, extended in MPI-3
* Focus here on "Remote Memory Access" (RMA)
* Basic idea: define a region of memory on each process, that other processes can read from or write to
* Target can be passive
* Needs locking!

#### Setup of the shared memory region

```julia
# set up an array of length N on each process and mark it shared
shared = zeros(N)
win = MPI.Win()
MPI.Win_create(shared, MPI.INFO_NULL, comm, win)
```

#### Have other ranks write the value of their rank to rank 0

```julia
# Every rank writes to the array held by rank 0 (dest) at its rank position
offset = rank
nb_elms = 1
MPI.Win_lock(MPI.LOCK_EXCLUSIVE, dest, no_assert, win)
MPI.Put([Float64(rank)], nb_elms, dest, offset, win)
MPI.Win_unlock(dest, win)
```

#### Read the array at rank 0
```julia
if rank == dest
  MPI.Win_lock(MPI.LOCK_SHARED, dest, no_assert, win)
  println("My partners sent me this: ", shared')
  MPI.Win_unlock(dest, win)
end
```

Output:
```text
My partners sent me this: [0.0 1.0 2.0 3.0]
```

## Application: MPIArrays

* Distributed array built around a per-processor Julia array that is shared as an MPI Window
* Implements `AbstractArray`
* Simple implementation

### How it works
See `src/simplempiarray.jl` file:
```julia
struct SimpleMPIVector{T} <: AbstractVector{T}
  localarray::Vector{T}
  comm::MPI.Comm
  win::MPI.Win

  function SimpleMPIVector{T}(comm::MPI.Comm, len) where {T}
    locarr = Vector{T}(undef, len)
    win = MPI.Win()
    MPI.Win_create(locarr, MPI.INFO_NULL, comm, win)
    return new{T}(locarr, comm, win)
  end
end
```

```julia
Base.IndexStyle(::Type{SimpleMPIVector{T}}) where {T} = IndexLinear()
Base.size(v::SimpleMPIVector) = size(v.localarray) .* MPI.Comm_size(v.comm)

function Base.getindex(v::SimpleMPIVector{T}, i::Int) where {T}
  loclen = length(v.localarray)
  target_rank = (i-1) ÷ loclen
  local_index = (i-1) % loclen
  result = Ref{T}()
  MPI.Win_lock(MPI.LOCK_SHARED, target_rank, 0, v.win)
  MPI.Get(result, 1, target_rank, local_index, v.win)
  MPI.Win_unlock(target_rank, v.win)
  return result[]
end
```

Usage example:
```julia
vec = SimpleMPIVector{Int}(comm, mylength)
rank == 0 && @show length(vec)

for i in mystart:myend
  vec[i] = rank
end

MPI.Barrier(comm)

rank == 0 && println("The global vector is ", vec')
```

Output of `mpirun -np 4 julia --project src/simplempiarray.jl`
```text
length(vec) = 16
The global vector is [0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3]
```

### MPIArrays.jl

* A more elaborate implementation of MPI-3 RMA based arrays can be found in [MPIArrays.jl](https://github.com/barche/MPIArrays.jl).
* Matrix-vector product example:

```julia
# Create an uninitialized matrix and vector
x = MPIArray{Float64}(N)
A = MPIArray{Float64}(N,N)

# Set local values
forlocalpart!(m -> fill!(m,1+rank),x)
forlocalpart!(m -> fill!(m,1+rank),A)
sync(A, x) # Make sure initialization is done everywhere

b = A*x
```

### Some MPIArrays features
* Distribute automatically or manually choose per-process size
* Initialize using existing local arrays
* `filter`
* Redistribute an array
* Extract a regular block to a local matrix
* `GhostedBlock` containing arbitrary off-processor entries
* Very limited linear algebra (only mat-vec, to test performance)

## Julia IO on top of MPI
Implemented in MPI.jl [PR 203](https://github.com/JuliaParallel/MPI.jl/pull/203). Example:

```julia
# winio receives data on all processes from anyone
const winio = WindowIO(comm)
# everyone can write to process 0
const writer = WindowWriter(winio, 0)

println(writer, "Hello from $rank")
flush(writer)

if rank == 0
  nb_received = 0
  while nb_received < MPI.Comm_size(comm)
    received = readline(winio)
    println("Received message: $received")
    global nb_received += 1
  end
end
```

Output of `mpirun -np 4 julia --project src/io.jl`:

```text
Received message: Hello from 0
Received message: Hello from 2
Received message: Hello from 1
Received message: Hello from 3
```

### Implemented functions
```julia
Base.nb_available(w::WindowIO)
Base.wait(w::WindowIO)
Base.isopen(w::WindowIO)
Base.eof(w::WindowIO)
Base.iswritable(::WindowIO)
Base.isreadable(::WindowIO)
Base.close(w::WindowIO)
Base.read(w::WindowIO, ::Type{UInt8})
Base.read(w::WindowIO, nb::Integer; all::Bool=true)
Base.readbytes!(w::WindowIO, b::AbstractVector{UInt8}, nb=length(b); all::Bool=true)
Base.readavailable(w::WindowIO)
Base.unsafe_read(w::WindowIO, p::Ptr{UInt8}, nb::UInt)
Base.write(w::WindowWriter, b::UInt8)
Base.unsafe_write(w::WindowWriter, p::Ptr{UInt8}, nb::UInt)
Base.flush(s::WindowWriter)
```

### Waiting for data
```julia
w.waiter = Task(function()
            wait(w.read_requested)
            while w.is_open
                while !has_data_available(w) && w.is_open
                    yield()
                end
                if w.is_open
                    notify(w.data_available)
                    wait(w.read_requested)
                end
            end
        end)

        yield(w.waiter)
```

## Clustermanager
* Manages communication for native Julia parallelism
* Communication using `TCPSocket <: IO`
* ClusterManagers based on MPI using `Send` and `Receive` existed
* New option using `IO`
* Intersperse MPI calls and native Julia

### ClusterManager mode

```julia
using Distributed, MPI
mgr = MPI.start_main_loop(MPI.MPI_WINDOW_IO)

@everywhere begin
  const comm = MPI.COMM_WORLD
  const vec = fill(1,10)
  s = MPI.Reduce(sum(vec), +, 0, comm)
end

println("Sum is $s")

@everywhere println("Hello from $(MPI.Comm_rank(comm))")

MPI.stop_main_loop(mgr)
```

Output of `mpirun -np 4 julia --project src/clustermanager.jl`:
```text
Sum is 40
Hello from 0
	From worker 3:	Hello from 2
	From worker 4:	Hello from 3
	From worker 2:	Hello from 1
```

### MPI mode

```julia
using Distributed, MPI
mgr = MPI.start_main_loop(MPI.MPI_WINDOW_NOWAIT)

const comm = MPI.COMM_WORLD
const vec = fill(1,10)
s = MPI.Reduce(sum(vec), +, 0, comm)

@cluster begin
  println("Sum is $s")
  @everywhere println("Hello from $(MPI.Comm_rank(comm))")
end

MPI.stop_main_loop(mgr)
```

## Some benchmarks
Single threaded `A*x`:
![Single threaded](figs/singlethread.svg)

## Some benchmarks
Multi-threaded `A*x`:
![Multi threaded](figs/multithread.svg)

## Conclusions
* MPI and Julia parallelism can work together
* Performance on-par with traditional codes
* ClusterManagers allow flexible choice between the Julia and MPI way, even in the same program
* My current use case: MPIArrays.jl

## Thanks

Many thanks to the [MPI.jl contributors](https://github.com/JuliaParallel/MPI.jl/graphs/contributors)